{% set name = "pypardiso" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff13eff486a2246d9c5bc9cec9f5bc8009f1b8831b2d10767787d768d98afa06

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm  # https://conda-forge.org/docs/maintainer/knowledge_base.html#using-setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - mkl <2024
    - numpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pypardiso

about:
  home: https://github.com/haasad/PyPardisoProject
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python interface to the Intel MKL Pardiso library to solve large sparse linear systems of equations

extra:
  recipe-maintainers:
    - cmutel
    - haasad
