{% set name = "pypardiso" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8eeafbda5fbf104162da2292fa69c190beee244acf3c95cdb6aac0edb3382bd1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - mkl

test:
  imports:
    - pypardiso
  requires:
    - pytest
  files:
    - tests/test_basic_solve.py
    - tests/test_input_A.py
    - tests/test_scipy_aliases.py
    - tests/test_input_b.py
  commands:
    - pytest -vv tests/

about:
  home: https://github.com/haasad/PyPardisoProject
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python interface to the Intel MKL Pardiso library to solve large sparse linear systems of equations

extra:
  recipe-maintainers:
    - cmutel
    - haasad
